karma-runner/karma-sauce-launcher

README.md, lib/sauce_launcher.js
This PR adds more CI generic env vars and resolves #82.
=> Add BUILD_NUMBER Compatibility For Drone And Other CI Systems.

README.md, lib/sauce_launcher.js, lib/sauce_reporter.js
I recently ran into an issue where the job update to sauce labs via the REST API module was hanging due to running our software behind a proxy.  The sauce labs  REST API module allows for specifying a proxy within the constructor, but it did not appear karma-sauce-launcher provided a property within the configuration to specify this attribute and pass it into that module's constructor.  So, I added the property to the config to specify the proxy, so our job update calls were successful.
=> Add proxy property to config to assist with Sauce REST API connection

README.md
It was pretty tricky to find the correct configuration for an Android test simulator.
I added an example and a link to the platform configurator Sauce Labs offers, since it helps a lot to find the correct values.
=> docs(README): add hint to platform configurator

README.md, lib/sauce_launcher.js
Tests with Sauce Connect have two connections to Sauce Labs, a
tunnel from Sauce Connect client to host, and Selenium commands themselves which are sent independently.
Sauce Connect is able to relay Selenium commands through the established tunnel, which helps obviate proxy and other issues with Selenium traffic.
This change adds config values `connectLocationForSERelay` and
`connectPortForSERelay` which allow users to make Karma send Selenium
commands through a Sauce Connect instance at that host and port.
=> Allow SE traffic to be sent via Sauce Connect's Relay.

.travis.yml, package.json, release.config.js
Executes `semantic-release` on Travis push builds of `master`.
Reference commit: https://github.com/karma-runner/karma-jasmine/commit/9b6e5f8987db4549ef8eeb95d89917ed10d736a6
Closes #176
=> chore(release): Enable semantic-release on karma-sauce-launcher

.travis.yml
The previous semantic-release PR failed because `TRAVIS_NODE_VERSION` was `stable`, not `12`. This PR fixes that check in the semantic-release Travis command (error due to copying the config from the other repo)
=> chore(semantic-release): update node version check in travis

README.md
semantic-release is working (at least within [GitHub releases](https://github.com/karma-runner/karma-sauce-launcher/releases/tag/v2.0.0), not NPM yet), so this PR adds the badge to the README
=> docs(readme): add semantic-release badge to README

.travis.yml, package.json
BREAKING CHANGE:  This PR eliminates the Node 8 runtime from package.json and the related Travis jobs/configuration.
=> chore(node): drop support for Node 8

package.json
BREAKING CHANGE:
Drop support for Node <10.
=> chore(release): force-trigger a semantic release

.travis.yml, package.json
@limonte @wswebcreation I'm going to try to merge this ASAP since it may fix the current broken state of the NPM package, but if you have comments/changes feel free to leave them here and I'll address in a follow-up
=> feat(release): add build step to semantic-release in Travis

src/launcher/launcher.ts
Removing unused heartbeat code to trigger a release, since #204 didn't
=> fix: remove heartbeat function

README.md, package.json, src/browser-info.ts, src/launcher/launcher.ts, src/local-tunnel/sauceconnect.ts, src/process-config.ts, src/reporter/reporter.ts, yarn.lock
This patch:
- updates the SauceLabs API binding to allow reporting to EU datacenters as well as on our headless platform
- update capabilities to be W3C conform (with backwards compatibility)
- replaces Selenium with WebdriverIO as it is better integrated into Sauce Labs (e.g. this will allow to run Karma tests on other DCs as well).
- removes proxy configurations as it is not recommended anymore to use the Sauce Connect relay
=> fix(deps): update SauceLabs API binding

README.md, examples/karma.conf-ci.js, package.json, src/browser-info.ts, src/launcher/launcher.ts, src/local-tunnel/sauceconnect.ts, src/process-config.ts, src/reporter/reporter.ts, yarn.lock
This PR came from @christian-bromann , see https://github.com/karma-runner/karma-sauce-launcher/pull/206 and has been merged to a local branch to be able to kick of the SL tests
=> Update sauce lib

README.md
Currently bermi's sauce-connect-launcher options is referenced but karma-sauce-launcher is now using Sauce Labs' own node-saucelabs to start the Sauce Connect tunnel.
=> docs(readme): fix Sauce Connect options link

package-lock.json, src/local-tunnel/sauceconnect.ts
Someone [reported](https://github.com/saucelabs/node-saucelabs/issues/86) an issue of Sauce Connect launcher failing with ENOENT which is normally impossible because we download Sauce Connect before we run it. It seems that there is a race condition where checking if the Sauce Connect binary was downloaded fails when looking for the version. The execution happens as follows:
1. check if the binary was downloaded
1. if no -> download
1. if yes continue
1. check if version is the one that has been downloaded
1. if no -> download expected version
1. if yes finish
The race condition seem to happen when the check if the binary exists was successful but then the consecutive version check fails if in between someone cleaned the binary which can happen in an CI/CD environment where dependencies …
=> Retry start Sauce Connect

src/launcher/launcher.ts
This PR re-implements the heartbeat which was reverted due to this issue https://github.com/karma-runner/karma-sauce-launcher/issues/198
=> feat: add heartbeat to keep session alive every 60 seconds

.gitignore, package-lock.json, package.json, src/browser-info.ts, src/launcher/launcher.ts, src/reporter/reporter.ts, src/utils.ts
This PR will add:
- replace the current Sauce Labs logs, which only contains a driver start and stop, with a new log that contains all the tests have been executed in this session
- execution urls to the logs so users can easily open the Sauce Labs execution
**Current reporting:**
**New success example:**
**New failure example:**
**Logs with execution url:**
=> feat: add test annotation

src/launcher/launcher.ts
This PR is based on https://github.com/karma-runner/karma-sauce-launcher/pull/160 and will fix https://github.com/karma-runner/karma-sauce-launcher/issues/159. 
It will fix the issue that the launcher didn't call the done callback when the concurrency configured in the Karma config was lower than the amount of instances that you want to run
=> fix: Call launcher done callback

src/process-config.ts
This PR fixes sending custom data to Sauce Labs and let the capabilities overwrite the generic information
=> fix: update sending custom information to Sauce Labs

src/reporter/reporter.ts
=> fix: fix reporter with browsers not launched through launcher
