karma-runner/karma-sauce-launcher

README.md

For beginners or system administrators that are interested in security it may be helpful to point out what kind of technology is used in the background.

Add information about Sauce Connect

---

.npmignore

v0.3.0 discloure a sauce_connect log generated by the repo owner.
@Dignifiedquire You should reset your SauceLabs credentials even if some data is masked with asterisks

Ignore log files before publish to NPM

---

README.md

docs: added supported platforms REST API link on Sauce Labs

---

lib/sauce_reporter.js

Fix for compatibility with newer Karma versions.

Fix for compatibility with newer Karma versions.

---

examples/karma.conf-ci.js
package.json

Pushing all dependencies to the latest version and the SauceLabs Karma configuration (based in the examples)
I ran one automated test with my personal account (maximum of 2 concurrent sessions), 
[]

Updating dependencies and SauceLabs configuration

---

package.json

Very out of date.
Should address #106

Upgrade sauce connect

---

lib/sauce_launcher.js

Pass parentTunnel to selenium

---

README.md

@dignifiedquire please squash merge this to adjust the commit message

Fixed SauceLabs doc links

---

lib/sauce_launcher.js

feat(launcher): expose commandTimeout, idleTimeout, maxDuration options

---

.travis.yml
package.json
src/launcher/launcher.ts

Allow reconnecting if Saucelabs terminated session

---

src/launcher/launcher.ts

Follow-up fix for https://github.com/karma-runner/karma-sauce-launcher/commit/6a9768dac32caa75287ac83a4a04d52fb746e848i

Fix misplaced try/catch not catching kill errors

---

examples/karma.conf-ci.js
src/launcher/launcher.ts

Needed functionality for determining whether a valid connection is still available to Sauce Labs via a heartbeat function.

added heartbeat functionality

---

.travis.yml
package.json
release.config.js
yarn.lock

Dupe of https://github.com/karma-runner/karma-sauce-launcher/pull/187 created as a PR against `master` to allow Sauce tests to run. Since that PR has approval, I'm going to go ahead and merge as soon as the tests pass.

chore(release): add npm publish config to semantic-release

---

package.json

Fixes https://github.com/karma-runner/karma-sauce-launcher/issues/190#issuecomment-606178228

No need to copy package.json to dist

---

src/launcher/launcher.ts

Adding a null check for heartbeat functionality for Sauce Labs.

added null check

---

src/launcher/launcher.ts

Dupe of #201 created on main repo so Sauce tests can execute.
Addresses #198
/cc @joshmgrant

Replace calls to renamed `.title()` with `.getTitle()`

---

src/launcher/launcher.ts

This PR is to revert some changes in commit 74eea92 as discussed in #198. I will be following up with a new changeset to solve this issue in the future.

Revert heartbeat changes

---

README.md

Reference commit: https://github.com/karma-runner/karma-jasmine/commit/40db343ad541fc286b20efcf963bd09fae490f30
Addresses #176 
Should not be merged until semantic-release configuration is completed.

docs(readme): Add semantic-release badge to README

---

examples/karma.conf-ci.js
package.json
src/launcher/launcher.ts
src/local-tunnel/sauceconnect.ts
src/process-config.ts
src/reporter/reporter.ts
yarn.lock

various improvements to the PR #207 that make the test finally pass: https://travis-ci.org/github/christian-bromann/karma-sauce-launcher/jobs/690699154

fix: start sauce connect via saucelabs package

---

src/reporter/reporter.ts

Fix #217 (the way it was after #87 before #156 rewrote the code)

initialize adapters

---

README.md
examples/karma.conf-ci.js
src/process-config.ts
src/utils.ts

This PR fixes https://github.com/karma-runner/karma-sauce-launcher/issues/210

fix: fixes issues with older browsers / caps

---

README.md

This PR fixes the docs which is related to https://github.com/karma-runner/karma-sauce-launcher/issues/133

chore: update mobile documentation

---

.editorconfig
package-lock.json
package.json
yarn.lock

Checked everything an there are no breaking changes
Add edit config

fix: update (dev)dependencies

---

src/reporter/reporter.ts

fix: correctly report test names and status

---

src/utils.ts

fix: make `waitUntil` retry logic work again

---

src/launcher/launcher.ts

Latest merge uploaded non existing files. This one disables the "new" logs and makes the result pass again

fix: temp fix to disable failing logs
